#!/bin/bash

plug_install_location=~/.vim/autoload/plug.vim
plug_download_location=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install / update vim-plug plugin manager:
if [ -f $plug_install_location ]; then
  vim +PlugUpgrade +qall
else
  curl -fLo $plug_install_location --create-dirs $plug_download_location
fi

# Now install plugins themselves:
vim +PlugUpdate +qall
