pipeline {
  agent {
    dockerfile {
      filename '.dot/Dockerfile'
    }
  }

  stages {
    // This will pull latest from master, not use
    // the currently-CI'd code...
    stage('Install dotfiles') {
      steps {
        sh '.dot/script/install'
      }
    }

    stage('Setup dotfiles') {
      steps {
        sh '.dot/script/setup'
      }
    }

    stage('Test installation') {
      steps {
        sh 'which fzf'
      }
    }
  }
}
