#!/bin/sh
set -e

# Clone a bare repository:
git clone --bare https://github.com/joshpencheon/dotfiles $HOME/.cfg

# Set up an alias for immediate use (see config.sh)
alias config='git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

# Checkout into $HOME:
config checkout

# Ignore untracked files (i.e. contents of $HOME)
config config --local status.showUntrackedFiles no

echo "Initialisation complete; you may want to run ~/.dot/scripts/setup now."
