#!/bin/bash

# ====== Use up-to-date bash by default ======

if ! fgrep -q '/usr/local/bin/bash' /etc/shells; then
  echo '/usr/local/bin/bash' | sudo tee -a /etc/shells;
  chsh -s /usr/local/bin/bash;
fi;

# ====== Install vim plugins ======

plug_install_location=~/.config/nvim/autoload/plug.vim
plug_download_location=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
if [ -f $plug_install_location ]; then
  vim +PlugUpgrade +qall
else
  curl -fLo $plug_install_location --create-dirs $plug_download_location
fi;
vim +PlugUpdate +qall
