#!/bin/bash

# ====== Use up-to-date bash by default ======

brewed_bash=/usr/local/bin/bash
if [ -x $brewed_bash ]; then
  if ! fgrep -q '/usr/local/bin/bash' /etc/shells; then
    echo '/usr/local/bin/bash' | sudo tee -a /etc/shells;
    chsh -s /usr/local/bin/bash;
  fi;
fi;

# ====== Install NeoVim plugins ======

nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

# ====== Compile bat themes ======

if command -v bat > /dev/null; then
  bat cache --build
else
  echo "Warning: skipping bat theme completion"
fi
