[control_center]
sidebar_section = "none"

    [control_center.calendar]
    show_events_card = false

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "dark_mode"
